"""add indexed_files table

Revision ID: 83d3b5b95773
Revises: 
Create Date: 2026-01-13 10:03:22.865189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d3b5b95773'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexed_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_account_id', sa.String(length=255), nullable=False),
    sa.Column('folder_id', sa.String(length=255), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('drive_url', sa.String(length=1000), nullable=True),
    sa.Column('indexing_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'drive_file_id', name='uq_user_drive_file')
    )
    op.create_index('ix_indexed_files_user_folder', 'indexed_files', ['user_id', 'folder_id'], unique=False)
    op.create_index('ix_indexed_files_user_status', 'indexed_files', ['user_id', 'indexing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_indexed_files_user_status', table_name='indexed_files')
    op.drop_index('ix_indexed_files_user_folder', table_name='indexed_files')
    op.drop_table('indexed_files')
    # ### end Alembic commands ###



